# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('margin_left', models.CharField(blank=True, default='auto', max_length=10)),
                ('margin_top', models.CharField(blank=True, default='auto', max_length=10)),
                ('margin_right', models.CharField(blank=True, default='auto', max_length=10)),
                ('margin_bottom', models.CharField(blank=True, default='auto', max_length=10)),
                ('padding_left', models.CharField(blank=True, default='auto', max_length=10)),
                ('padding_top', models.CharField(blank=True, default='auto', max_length=10)),
                ('padding_right', models.CharField(blank=True, default='auto', max_length=10)),
                ('padding_bottom', models.CharField(blank=True, default='auto', max_length=10)),
                ('position', models.CharField(choices=[('static', 'static'), ('relative', 'relative'), ('fixed', 'fixed'), ('absolute', 'absolute')], default='static', max_length=9)),
                ('font_size', models.IntegerField(default=12)),
                ('font_family', models.CharField(choices=[('Times New Roman', 'Times New Roman'), ('Georgia', 'Georgia'), ('Times', 'Times'), ('Arial', 'Arial'), ('Helvetica', 'Helvetica')], default='Arial', max_length=20)),
                ('generic_family', models.CharField(choices=[('serif', 'serif'), ('sans-serif', 'sans-seri'), ('cursive', 'cursive'), ('fantasy', 'fantasy'), ('monospace', 'monospace')], default='serif', max_length=10)),
                ('italic', models.BooleanField(default=False)),
                ('bold', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
