# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfield',
            name='color',
            field=models.CharField(default='black', max_length=15),
        ),
    ]
