# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_auto_20170411_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfield',
            name='font_size',
            field=models.CharField(default='12px', max_length=15),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='generic_family',
            field=models.CharField(choices=[('serif', 'serif'), ('sans-serif', 'sans-serif'), ('cursive', 'cursive'), ('fantasy', 'fantasy'), ('monospace', 'monospace')], default='serif', max_length=10),
        ),
    ]
